### ISSUE TITLE
Create a tagged version

### ISSUE THREAD

**Issue by bavovanachte** [pfalcon/sphinx_selective_exclude#1]
Hi,

Could you please apply a tag on your repository? We aim to submodule your project for our documentation, and we generally aim to submodule only released versions.

**Comment by pfalcon** [comment]
Done: https://github.com/pfalcon/sphinx_selective_exclude/releases/tag/1.0

Feel free to share link to your project, so I knew who're the users of sphinx_selective_exclude.

**Comment by bavovanachte** [comment]
Sadly, I cannot share it, as it is a corporate project, but it will normally be used by a number of people in the company, so we'll provide feedback whenever we can. Thanks for the effort, it's already solving a lot of issues we had with the only directive in combination with the sphinxcontrib-traceability extension.
