### ISSUE TITLE
Publish package to pypi

### ISSUE THREAD

**Issue by bavovanachte** [pfalcon/sphinx_selective_exclude#3]
Hi again,

Could you publish this package to pypi? We're trying to minimize the number of submodules.
I can always publish it to our company (non-public) pypi server, but if you would publish it to the public pypi server, that would be even better.

Thanks,

Bavo

**Comment by pfalcon** [comment]
Sounds good. Please give me a week or two (I'm currently at the conference), I'll do that.

**Comment by bavovanachte** [comment]
If it helps, I already proposed some infrastructure for the pip upload in PR #4.

**Comment by pfalcon** [comment]
Resolved via https://github.com/pfalcon/sphinx_selective_exclude/pull/4 . Please reopen in case of any issues.

**Comment by bavovanachte** [comment]
Thanks a lot. Tested with version 1.0.1 from pypi, and it integrates nicely in a sphinx project (just have to change it to ```sphinx_selective_include.eager_only``` instead of just ```eager_only```

**Comment by pfalcon** [comment]
Thanks for verifying!
