### ISSUE TITLE
Package version 1.0.2 on PyPI does not work 

### ISSUE THREAD

**Issue by JasperCraeghs** [pfalcon/sphinx_selective_exclude#9]
When using `sphinx_selective_exclude==1.0.2` installed via pip3, I get the error below when building documentation. (in [Travis CI](https://travis-ci.org/melexis/sphinx-traceability-extension/jobs/628661103) too)
```
Extension error:
Could not import extension sphinx_selective_exclude.eager_only (exception: No module named 'sphinx_selective_exclude')
```
Version 1.0.1 works just fine.

I did some research and found out on [packaging.python.org](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata) that, since you're now using GitHub-flavored Markdown to write the project’s description, you need to upgrade some of your modules on your machine or simply set up Travis CI to build and upload the package for you when you make a tag.

**Comment by pfalcon** [comment]
Should be fixed by 1.0.3 just released.
